name: Trigger auto deployment for swiftfiddle-runner-functions-602

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/swiftfiddle-runner-functions-602-AutoDeployTrigger-bb8bc7d5-c427-4afd-835e-cf5ef5f46b59.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS602_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS602_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS602_REGISTRY_PASSWORD }}
          containerAppName: swiftfiddle-runner-functions-602
          resourceGroup: swiftfiddle
          imageToBuild: swiftfiddle/swiftfiddle-runner-functions-602:latest
